name: Build Docker Images
on:
    workflow_dispatch:

jobs:
  build-voiceware:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main 
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: cyrenity
        password: ${{ github.token || secrets.GH_TOKEN }}
   
    - name: Build the django app image
      run: |
        docker build . \
            --tag ghcr.io/cyrenity/tempo-app:latest \
            --tag ghcr.io/cyrenity/tempo-app:${GITHUB_SHA::7} 
        docker push ghcr.io/cyrenity/tempo-app:latest
        docker push ghcr.io/cyrenity/tempo-app:${GITHUB_SHA::7}
