name: Build Docker Images
on:
    workflow_call:
        inputs:
          semver:
            required: true
            type: string

jobs:
  build-voiceware:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main 
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Normalize version string for docker tag
      id: docker-tag
      run: |
          echo "${{ inputs.semver }}"
          ver=`echo "${{ inputs.semver }}" | sed 's/\+/-/'`
          echo "$ver"
          echo "dockertag=$ver" >> $GITHUB_OUTPUT
    - name: Build the django app image
      run: |
        docker build . \
            --tag ghcr.io/cyrenity/tempo-app:latest \
            --tag ghcr.io/cyrenity/tempo-app:${{ steps.docker-tag.outputs.dockertag }} 
        docker push ghcr.io/cyrenity/tempo-app:latest
        docker push ghcr.io/cyrenity/tempo-app:${{ steps.docker-tag.outputs.dockertag }}
