name: Deploy to Staging

on:
  workflow_dispatch:
  workflow_call:

jobs:
  staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://example.com
      
    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan -H ${{ secrets.STAGING_SERVER_IP }} >> ~/.ssh/known_hosts
        
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: cyrenity/apidemo
        path: apidemo
        
    - name: run on deployment host
      run: |
        ssh -l ${{ secrets.STAGING_SERVER_USER}} ${{ secrets.STAGING_SERVER_IP }} "ip addr sh"
