name: Health-Check 
on:
  pull_request:
    branches: [ "main" ]
  workflow_call: 
  
jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check code health
      run: |
        echo "Running health check job!"
